[project]
name = 'Stellar-Lifecycle-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.engineering-projects]
path = 'contracts/engineering-projects.clar'
clarity_version = 2
epoch = 2.5

[contracts.stellar-parameters]
path = 'contracts/stellar-parameters.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
